SELECT  [Donation_ID]
      ,[Donor_ID]
      ,[TestResult]
      ,[Heartbeat]
      ,[bloodpressure_Min]
      ,[bloodpressure_Max]
      ,[BodyTemprature]
      ,[Bloodstream_confirm]
      ,[Questionnaire_Confirm]
      ,[pupil_confirm]
      ,[behavior_confirm]
      ,[HB_Reciption1_Sys]
      ,[HB_Reciption2_Sys]

      ,[RBC1]
      ,[RBC2]
      ,[WBC1]
      ,[WBC2]
      ,[PLT1]
      ,[PLT2]
      ,[MCV1]
      ,[MCV2]
      ,[MCHC1]
      ,[MCHC2]
      ,[HCT1]
      ,[HCT2]
      ,[HB_Reciption1_Hemo]
      ,[HB_Reciption2_Hemo]
      ,[Reciption_Date]
      ,[Reciption_Time]
      ,[HB_Medic]
      ,[Viro_serum]
      ,[Plasma]
      ,[status_physician]
      ,[justificationDonat_Time]
	  ,DATEDIFF(minute, [Reciption_Time], [justificationDonat_Time])Recipt2Justification
      ,[DonatSec_EnteryTime]
	  ,DATEDIFF(minute, [justificationDonat_Time], [DonatSec_EnteryTime]) Justification2DonatSec
      ,[Device_ID]
      ,[Arm]
      ,[Venip_Time]
      ,[Device_SetTime]
      ,[Proc_StartTime]
      ,[Proc_EndTime]
	  ,DATEDIFF(minute,  [Proc_StartTime],[Proc_EndTime]) start2EndProc
	  ,DATEDIFF(minute,  [Reciption_Time],[Proc_EndTime]) Recipt2EndProc
      ,[MedicMass_Plasma]
      ,[DonationMass_plasma]
      ,[Donateloss_blood]
      ,[Proc_End_User_ID]
      ,[Proc_End_Time]
      ,[Heartbeat_release]
      ,[bp_Min_release]
      ,[bp_Max_release]
      ,[BodyTemprature_release]
      ,[Cash_Bon]
      ,[Cash_Total]
      ,[Cash_Donation]
      ,[release_Time]
      ,[Payment_Time]
	  ,DATEDIFF(minute,  [Reciption_Time],[Payment_Time]) Recit2Payment
      ,[Plasma_totalWeight]
      ,[Plasma_btl_weight]
      ,[Plasma_real_volume]
      ,[Product_Manage_Confirm]
      ,[Product_QC_Confirm]
      ,[Product_QP_Confirm]
      ,[Status_Donation]
      ,[Donate_successful_status]
      ,[physician_confirm]
      ,[Plasma_Status]
      ,[Donor_health_status]
      ,[Donor_Status]
      ,[Save_Date]
      ,[Save_time]
      ,[LastUpdate_UserID]
      ,[LastUpdate_Date]
      ,[LastUpdate_Time]
      ,[MCH1]
      ,[MCH2]
      ,[CUE]
      ,[UID]
      ,[TC]
      ,[PID]
  FROM [Plasma].[dbo].[Tbl_donations]
