USE [master]
GO

/****** Object:  Database [Stage]    Script Date: 2/22/2025 9:24:29 AM ******/
CREATE DATABASE [Stage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Stage', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Stage.mdf' , SIZE = 9034560KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'Stage_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Stage_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Stage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Stage] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Stage] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Stage] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Stage] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Stage] SET ARITHABORT OFF 
GO

ALTER DATABASE [Stage] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Stage] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [Stage] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Stage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Stage] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Stage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Stage] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Stage] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Stage] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Stage] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Stage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Stage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Stage] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Stage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Stage] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Stage] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Stage] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Stage] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Stage] SET  MULTI_USER 
GO

ALTER DATABASE [Stage] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Stage] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Stage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Stage] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Stage] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Stage] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Stage] SET QUERY_STORE = ON
GO

ALTER DATABASE [Stage] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Stage] SET  READ_WRITE 
GO


